#!/usr/bin/env python
# -*- coding: utf-8 -*-
try:
    from tkinter import *    #  python 3.
except:
    from Tkinter import *    #  python 2.7
    
from random import randint   # MÓDULO RANDOM-ALEATORIO

def main():
    
    def roll(): # Función que lanza el dado
        mitext.delete(0.0,END) # borrar contenido de mitext   Text.
        numero =  str(randint(0,99999)) # número del 0 al 99999 en formato texto
        numero = "%05d" % (randint(0,99999)) # Poner los 0 a la izquierda
        mitext.insert(END,numero) # escribir número en mitext
        #Número premiado termina en 3
        if (int(numero)-3)%10==0:
            premio.pack() #Hacer visible el widget
        else:
            premio.pack_forget()
            #print("🤑  Número premiado 🤑")
        
       

    # Ventana principal
    window=Tk() 
    window.title('Text , Button, Random')
    window.config(background = 'green')

   # Widgets
    mitext=Text(window,width=5,height=1,font = ('Arial',44)) 
    buttonA=Button(window,text='Generar Número',command=roll,font = ('Arial',22))    
    mitext.pack(pady=20 )
    buttonA.pack(fill=X, padx=20,pady=20 ,ipadx=20,ipady=10)
    premio=Label(window,text='🤑  Número premiado 🤑',font = ('Arial',22), justify=RIGHT)
    window.mainloop()
    
    

    
    
        
if __name__ == "__main__":       # averiguar si se está ejecutando o importando
        main()
